version: '3.8'

services:
  # Reference container: chromedp/headless-shell
  benchmark-chromedp:
    image: chromedp/headless-shell:latest
    container_name: benchmark-chromedp
    ports:
      - "9222:9222"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2G
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Thorium AVX2 version
  benchmark-thorium-avx2:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        THORIUM_VERSION: M130.0.6723.174
        INSTRUCTION_SET: AVX2
    container_name: benchmark-thorium-avx2
    ports:
      - "9223:9222"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2G
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Thorium AVX version
  benchmark-thorium-avx:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        THORIUM_VERSION: M130.0.6723.174
        INSTRUCTION_SET: AVX
    container_name: benchmark-thorium-avx
    ports:
      - "9224:9222"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2G
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Thorium SSE3 version
  benchmark-thorium-sse3:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        THORIUM_VERSION: M130.0.6723.174
        INSTRUCTION_SET: SSE3
    container_name: benchmark-thorium-sse3
    ports:
      - "9225:9222"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2G
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Thorium SSE4 version
  benchmark-thorium-sse4:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        THORIUM_VERSION: M130.0.6723.174
        INSTRUCTION_SET: SSE4
    container_name: benchmark-thorium-sse4
    ports:
      - "9226:9222"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2G
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Benchmark runner
  benchmark-runner:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: benchmark-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - benchmark-chromedp
      - benchmark-thorium-avx2
      - benchmark-thorium-avx
      - benchmark-thorium-sse3
      - benchmark-thorium-sse4
    restart: "no" 